### ISSUE TITLE
[CRJS205][team5R] : Avoid autocomplete fields

### ISSUE THREAD

**Issue by Silicoman** [green-code-initiative/ecoCode-javascript#8]
Team 5R

**Comment by utarwyn** [comment]
Hello! It's just an idea or did you have time to work on it?
I think it's more an HTML rule, we are discussing in #4 to add support for this language

**Comment by Silicoman** [comment]
Hi, we have not yet done the pull request about this. My collegue @Houssainatou is working about fixing an error we detect at the end of hackathon. She has shared me she will try to close this ticket this weekend.
It's actually on : https://github.com/Silicoman/ecoCode-linter-5R/tree/CR205-JS 
I will be back next week with more info.

**Comment by utarwyn** [comment]
Hello,
I think your rule idea refers to [this article](http://www.ecometer.org/rules/use-input-help-instead-of-autocomplete.html) which explains that a field should not be autocomplete with data from the server, as this causes a lot of network calls and CPU consumption. However, the implementation of your rule assumes that you don't use the "autocomplete" attribute on an "input" element, but **it doesn't serve the same purpose**. It allows the browser to pre-fill fields with data already known ([see doc here](https://developer.mozilla.org/docs/Web/HTML/Attributes/autocomplete)).

I'm therefore closing this ticket, as I don't think this rule is applicable as it stands. I leave it to you to reopen a ticket in the ecoCode repository to discuss a new rule to limit network calls of an auto-completion system.
